# Generated by Django 5.1.5 on 2025-01-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_progress_date_alter_progress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.employee'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('assignment', 'employee', 'date')},
        ),
    ]
